pool:
  vmImage: Hosted macOS
  demands: xcode

steps:
- task: CocoaPods@0
  displayName: 'pod install'

- task: Xcode@5
  displayName: 'Xcode build'
  inputs:
    xcWorkspacePath: 'Hakawai.xcworkspace'
    scheme: 'Hakawai'
    xcodeVersion: '10'
