trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: Hosted macOS
  demands: xcode

steps:
- task: CocoaPods@0
  displayName: 'pod install'

- task: Xcode@5
  displayName: 'Xcode build'
  inputs:
    xcWorkspacePath: 'Hakawai.xcworkspace'
    scheme: 'Hakawai'
    xcodeVersion: '10'

- task: Xcode@5
  displayName: 'Xcode test'
  inputs:
    actions: test
    configuration: Debug
    sdk: iphonesimulator
    xcWorkspacePath: 'Hakawai.xcworkspace'
    scheme: 'Hakawai'
    xcodeVersion: '10'
    destinationPlatformOption: iOS
    destinationSimulators: 'iPhone X'
    publishJUnitResults: true
